export async function fetchClients() { const res = await fetch("/api/clients"); if (!res.ok) throw new Error("Failed"); return res.json(); }
export async function fetchInvoices() { const res = await fetch("/api/invoices"); if (!res.ok) throw new Error("Failed"); return res.json(); }
export async function fetchInvoice(id: string) { const res = await fetch(`/api/invoices/${id}`); if (!res.ok) throw new Error("Failed"); return res.json(); }
export async function createInvoice(data: any) { const res = await fetch("/api/invoices", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); if (!res.ok) { const e = await res.json(); throw new Error(e.error || "Failed"); } return res.json(); }
export async function updateInvoice(id: string, data: any) { const res = await fetch(`/api/invoices/${id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); if (!res.ok) { const e = await res.json(); throw new Error(e.error || "Failed"); } return res.json(); }
export async function deleteInvoice(id: string) { const res = await fetch(`/api/invoices/${id}`, { method: "DELETE" }); if (!res.ok) throw new Error("Failed"); return res.json(); }
export async function createClient(data: any) { const res = await fetch("/api/clients", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(data) }); if (!res.ok) { const e = await res.json(); throw new Error(e.error || "Failed"); } return res.json(); }
export async function deleteClient(id: string) { const res = await fetch(`/api/clients/${id}`, { method: "DELETE" }); if (!res.ok) { const e = await res.json(); throw new Error(e.error || "Failed"); } return res.json(); }
export async function generateNextInvoiceNo() { const invoices = await fetchInvoices(); const nums = invoices.map((inv: any) => { const m = inv.invoiceNo?.match(/INV-(\d+)/); return m ? parseInt(m[1]) : 0; }); return `INV-${String((nums.length > 0 ? Math.max(...nums) : 0) + 1).padStart(4, "0")}`; }
